-- ============================================================
-- Fuel Station Shift Reconciliation System
-- Database Migration V2
-- Purpose: Create organization and fuel station master tables
-- ============================================================


-- ============================================================
-- Organization
-- ============================================================

CREATE TABLE reconciliation.organization (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_code VARCHAR(30) NOT NULL,
    organization_name VARCHAR(150) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ,
    updated_by BIGINT,

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT uk_organization_code
        UNIQUE (organization_code),

    CONSTRAINT ck_organization_code_not_blank
        CHECK (BTRIM(organization_code) <> ''),

    CONSTRAINT ck_organization_name_not_blank
        CHECK (BTRIM(organization_name) <> '')
);


-- ============================================================
-- Fuel Station
-- ============================================================

CREATE TABLE reconciliation.fuel_station (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id BIGINT NOT NULL,

    station_code VARCHAR(30) NOT NULL,
    station_name VARCHAR(150) NOT NULL,

    address_line_1 VARCHAR(200),
    address_line_2 VARCHAR(200),
    city VARCHAR(100),
    state VARCHAR(100),
    postal_code VARCHAR(20),

    time_zone VARCHAR(60) NOT NULL DEFAULT 'Asia/Kolkata',
    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ,
    updated_by BIGINT,

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_fuel_station_organization
        FOREIGN KEY (organization_id)
        REFERENCES reconciliation.organization (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_fuel_station_organization_code
        UNIQUE (organization_id, station_code),

    CONSTRAINT ck_fuel_station_code_not_blank
        CHECK (BTRIM(station_code) <> ''),

    CONSTRAINT ck_fuel_station_name_not_blank
        CHECK (BTRIM(station_name) <> ''),

    CONSTRAINT ck_fuel_station_time_zone_not_blank
        CHECK (BTRIM(time_zone) <> '')
);


-- ============================================================
-- Indexes
-- ============================================================

CREATE INDEX idx_fuel_station_organization_active
    ON reconciliation.fuel_station (organization_id, active);