-- ============================================================
-- Fuel Station Shift Reconciliation System
-- Database Migration V3
-- Purpose:
--   Create dispenser unit, fuel type, and nozzle master tables
-- ============================================================


-- ============================================================
-- Dispenser Unit
-- ============================================================

CREATE TABLE reconciliation.dispenser_unit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    fuel_station_id BIGINT NOT NULL,

    du_serial_number VARCHAR(100) NOT NULL,
    normalized_du_serial_number VARCHAR(100) NOT NULL,
    display_name VARCHAR(150) NOT NULL,

    manufacturer VARCHAR(100),
    model_number VARCHAR(100),

    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ,
    updated_by BIGINT,

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_dispenser_unit_fuel_station
        FOREIGN KEY (fuel_station_id)
        REFERENCES reconciliation.fuel_station (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_dispenser_unit_normalized_serial
        UNIQUE (normalized_du_serial_number),

    CONSTRAINT ck_dispenser_unit_serial_not_blank
        CHECK (BTRIM(du_serial_number) <> ''),

    CONSTRAINT ck_dispenser_unit_normalized_serial_not_blank
        CHECK (BTRIM(normalized_du_serial_number) <> ''),

    CONSTRAINT ck_dispenser_unit_display_name_not_blank
        CHECK (BTRIM(display_name) <> '')
);


-- ============================================================
-- Fuel Type
-- ============================================================

CREATE TABLE reconciliation.fuel_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    fuel_code VARCHAR(30) NOT NULL,
    fuel_name VARCHAR(100) NOT NULL,

    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ,
    updated_by BIGINT,

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT uk_fuel_type_code
        UNIQUE (fuel_code),

    CONSTRAINT ck_fuel_type_code_not_blank
        CHECK (BTRIM(fuel_code) <> ''),

    CONSTRAINT ck_fuel_type_name_not_blank
        CHECK (BTRIM(fuel_name) <> '')
);


-- ============================================================
-- Nozzle
-- ============================================================

CREATE TABLE reconciliation.nozzle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    dispenser_unit_id BIGINT NOT NULL,
    fuel_type_id BIGINT NOT NULL,

    nozzle_number INTEGER NOT NULL,

    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ,
    updated_by BIGINT,

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_nozzle_dispenser_unit
        FOREIGN KEY (dispenser_unit_id)
        REFERENCES reconciliation.dispenser_unit (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_nozzle_fuel_type
        FOREIGN KEY (fuel_type_id)
        REFERENCES reconciliation.fuel_type (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_nozzle_dispenser_unit_number
        UNIQUE (dispenser_unit_id, nozzle_number),

    CONSTRAINT ck_nozzle_number_positive
        CHECK (nozzle_number > 0)
);


-- ============================================================
-- Indexes
-- ============================================================

CREATE INDEX idx_dispenser_unit_station_active
    ON reconciliation.dispenser_unit (fuel_station_id, active);

CREATE INDEX idx_nozzle_dispenser_active
    ON reconciliation.nozzle (dispenser_unit_id, active);

CREATE INDEX idx_nozzle_fuel_type
    ON reconciliation.nozzle (fuel_type_id);