-- ============================================================
-- Fuel Station Shift Reconciliation System
-- Database Migration V4
-- Purpose:
--   Create employee, fuel price, and cash denomination
--   master tables
-- ============================================================


-- ============================================================
-- Employee
-- ============================================================

CREATE TABLE reconciliation.employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id BIGINT NOT NULL,

    employee_code VARCHAR(30) NOT NULL,
    employee_name VARCHAR(150) NOT NULL,

    mobile_number VARCHAR(30),
    email_address VARCHAR(150),
    aadhaar_number VARCHAR(20),

    address_line_1 VARCHAR(200),
    address_line_2 VARCHAR(200),
    city VARCHAR(100),
    state VARCHAR(100),
    postal_code VARCHAR(20),

    photograph_storage_path VARCHAR(1000),

    date_of_joining DATE NOT NULL,
    date_of_leaving DATE,

    employment_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ,
    updated_by BIGINT,

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_employee_organization
        FOREIGN KEY (organization_id)
        REFERENCES reconciliation.organization (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_employee_organization_code
        UNIQUE (organization_id, employee_code),

    CONSTRAINT ck_employee_code_not_blank
        CHECK (BTRIM(employee_code) <> ''),

    CONSTRAINT ck_employee_name_not_blank
        CHECK (BTRIM(employee_name) <> ''),

    CONSTRAINT ck_employee_leaving_date
        CHECK (
            date_of_leaving IS NULL
            OR date_of_leaving >= date_of_joining
        ),

    CONSTRAINT ck_employee_employment_status
        CHECK (
            employment_status IN (
                'ACTIVE',
                'INACTIVE',
                'LEFT'
            )
        ),

    CONSTRAINT ck_employee_left_requires_leaving_date
        CHECK (
            employment_status <> 'LEFT'
            OR date_of_leaving IS NOT NULL
        )
);


-- ============================================================
-- Fuel Price
-- ============================================================

CREATE TABLE reconciliation.fuel_price (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    fuel_station_id BIGINT NOT NULL,
    fuel_type_id BIGINT NOT NULL,

    price_per_litre NUMERIC(12, 3) NOT NULL,

    effective_from TIMESTAMPTZ NOT NULL,
    effective_to TIMESTAMPTZ,

    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ,
    updated_by BIGINT,

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_fuel_price_station
        FOREIGN KEY (fuel_station_id)
        REFERENCES reconciliation.fuel_station (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_fuel_price_fuel_type
        FOREIGN KEY (fuel_type_id)
        REFERENCES reconciliation.fuel_type (id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_fuel_price_positive
        CHECK (price_per_litre > 0),

    CONSTRAINT ck_fuel_price_effective_period
        CHECK (
            effective_to IS NULL
            OR effective_to > effective_from
        )
);


-- ============================================================
-- Cash Denomination
-- ============================================================

CREATE TABLE reconciliation.cash_denomination (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    currency_code CHAR(3) NOT NULL,
    denomination_value NUMERIC(12, 2) NOT NULL,
    display_order INTEGER NOT NULL,

    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ,
    updated_by BIGINT,

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT uk_cash_denomination_currency_value
        UNIQUE (currency_code, denomination_value),

    CONSTRAINT ck_cash_denomination_currency_not_blank
        CHECK (BTRIM(currency_code) <> ''),

    CONSTRAINT ck_cash_denomination_value_positive
        CHECK (denomination_value > 0),

    CONSTRAINT ck_cash_denomination_display_order_positive
        CHECK (display_order > 0)
);


-- ============================================================
-- Indexes
-- ============================================================

CREATE INDEX idx_employee_organization_status
    ON reconciliation.employee (
        organization_id,
        employment_status
    );

CREATE INDEX idx_employee_joining_date
    ON reconciliation.employee (date_of_joining);

CREATE INDEX idx_employee_leaving_date
    ON reconciliation.employee (date_of_leaving);

CREATE INDEX idx_fuel_price_station_fuel_dates
    ON reconciliation.fuel_price (
        fuel_station_id,
        fuel_type_id,
        effective_from,
        effective_to
    );