-- ============================================================
-- Fuel Station Shift Reconciliation System
-- Database Migration V5
-- Purpose:
--   Create application user, role, user-role,
--   and station-access security tables
-- ============================================================


-- ============================================================
-- Application User
-- ============================================================

CREATE TABLE reconciliation.application_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id BIGINT NOT NULL,
    employee_id BIGINT,

    username VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(150) NOT NULL,

    active BOOLEAN NOT NULL DEFAULT TRUE,
    account_locked BOOLEAN NOT NULL DEFAULT FALSE,
    password_change_required BOOLEAN NOT NULL DEFAULT TRUE,

    failed_login_count INTEGER NOT NULL DEFAULT 0,
    last_login_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ,
    updated_by BIGINT,

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_application_user_organization
        FOREIGN KEY (organization_id)
        REFERENCES reconciliation.organization (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_application_user_employee
        FOREIGN KEY (employee_id)
        REFERENCES reconciliation.employee (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_application_user_organization_username
        UNIQUE (organization_id, username),

    CONSTRAINT ck_application_user_username_not_blank
        CHECK (BTRIM(username) <> ''),

    CONSTRAINT ck_application_user_password_hash_not_blank
        CHECK (BTRIM(password_hash) <> ''),

    CONSTRAINT ck_application_user_display_name_not_blank
        CHECK (BTRIM(display_name) <> ''),

    CONSTRAINT ck_application_user_failed_login_count
        CHECK (failed_login_count >= 0)
);


-- ============================================================
-- Role
-- ============================================================

CREATE TABLE reconciliation.role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    role_code VARCHAR(50) NOT NULL,
    role_name VARCHAR(100) NOT NULL,

    active BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uk_role_code
        UNIQUE (role_code),

    CONSTRAINT ck_role_code_not_blank
        CHECK (BTRIM(role_code) <> ''),

    CONSTRAINT ck_role_name_not_blank
        CHECK (BTRIM(role_name) <> '')
);


-- ============================================================
-- User Role
-- ============================================================

CREATE TABLE reconciliation.user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,

    CONSTRAINT pk_user_role
        PRIMARY KEY (user_id, role_id),

    CONSTRAINT fk_user_role_user
        FOREIGN KEY (user_id)
        REFERENCES reconciliation.application_user (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_user_role_role
        FOREIGN KEY (role_id)
        REFERENCES reconciliation.role (id)
        ON DELETE RESTRICT
);


-- ============================================================
-- User Station Access
-- ============================================================

CREATE TABLE reconciliation.user_station_access (
    user_id BIGINT NOT NULL,
    fuel_station_id BIGINT NOT NULL,

    CONSTRAINT pk_user_station_access
        PRIMARY KEY (user_id, fuel_station_id),

    CONSTRAINT fk_user_station_access_user
        FOREIGN KEY (user_id)
        REFERENCES reconciliation.application_user (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_user_station_access_station
        FOREIGN KEY (fuel_station_id)
        REFERENCES reconciliation.fuel_station (id)
        ON DELETE RESTRICT
);


-- ============================================================
-- Indexes
-- ============================================================

CREATE INDEX idx_application_user_organization_active
    ON reconciliation.application_user (
        organization_id,
        active
    );

CREATE INDEX idx_application_user_employee
    ON reconciliation.application_user (employee_id);

CREATE INDEX idx_application_user_username
    ON reconciliation.application_user (username);