-- ============================================================
-- Fuel Station Shift Reconciliation System
-- Database Migration V6
--
-- Purpose:
--   1. Introduce configurable dispenser-side master data.
--   2. Introduce effective-dated nozzle fuel-type assignments.
--   3. Introduce configurable shift definitions.
--   4. Create operational shift, employee working-time,
--      dispenser participation and nozzle-assignment tables.
--
-- Important:
--   - A physical DU may contain multiple logical sides.
--   - Side names are configurable (A/B, Front/Back, etc.).
--   - Each nozzle belongs to one dispenser side.
--   - Fuel type is configured independently for each nozzle.
--   - Fuel-type changes must preserve historical configuration.
--   - A station shift may operate one or more dispenser units.
-- ============================================================


-- ============================================================
-- 1. Dispenser Side
--
-- Represents one logical/physical operating face of a
-- dispenser unit.
--
-- Examples:
--   A / B
--   Front / Back
--   North / South
--   East / West
--
-- The application must not hard-code any particular naming
-- convention.
-- ============================================================

CREATE TABLE reconciliation.dispenser_side (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    dispenser_unit_id BIGINT NOT NULL,

    side_name VARCHAR(50) NOT NULL,

    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ,
    updated_by BIGINT,

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_dispenser_side_dispenser_unit
        FOREIGN KEY (dispenser_unit_id)
        REFERENCES reconciliation.dispenser_unit (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_dispenser_side_unit_name
        UNIQUE (
            dispenser_unit_id,
            side_name
        ),

    CONSTRAINT ck_dispenser_side_name_not_blank
        CHECK (
            BTRIM(side_name) <> ''
        )
);


-- ============================================================
-- 2. Associate Nozzle with Dispenser Side
--
-- The nozzle table already exists from V3.
--
-- Each nozzle now belongs to one configured dispenser side.
--
-- Example:
--
--   DU-01
--     Side A
--       N1
--       N2
--
--     Side B
--       N3
--       N4
--
-- No nozzle-number-to-side rule shall be hard-coded.
-- ============================================================

ALTER TABLE reconciliation.nozzle
    ADD COLUMN dispenser_side_id BIGINT;


ALTER TABLE reconciliation.nozzle
    ADD CONSTRAINT fk_nozzle_dispenser_side
        FOREIGN KEY (dispenser_side_id)
        REFERENCES reconciliation.dispenser_side (id)
        ON DELETE RESTRICT;


-- At this development stage the nozzle table is expected to
-- contain no production/master records.
--
-- If unexpected nozzle data exists, this statement deliberately
-- fails instead of assigning an incorrect dispenser side.
-- ============================================================

ALTER TABLE reconciliation.nozzle
    ALTER COLUMN dispenser_side_id SET NOT NULL;


-- ============================================================
-- 3. Nozzle Fuel-Type Assignment
--
-- Fuel type is not a permanent physical property of a nozzle.
--
-- The station administrator may reconfigure a nozzle from one
-- fuel type to another after a period of time.
--
-- Historical assignments must remain available so previous
-- shift calculations retain their original meaning.
--
-- Example:
--
--   N1 -> PETROL
--       effective_from = 2026-01-01
--       effective_to   = 2026-11-30
--
--   N1 -> DIESEL
--       effective_from = 2026-12-01
--       effective_to   = NULL
--
-- Overlapping effective periods will initially be prevented
-- transactionally by the application service.
-- ============================================================

CREATE TABLE reconciliation.nozzle_fuel_type_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nozzle_id BIGINT NOT NULL,
    fuel_type_id BIGINT NOT NULL,

    effective_from TIMESTAMPTZ NOT NULL,
    effective_to TIMESTAMPTZ,

    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ,
    updated_by BIGINT,

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_nozzle_fuel_assignment_nozzle
        FOREIGN KEY (nozzle_id)
        REFERENCES reconciliation.nozzle (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_nozzle_fuel_assignment_fuel_type
        FOREIGN KEY (fuel_type_id)
        REFERENCES reconciliation.fuel_type (id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_nozzle_fuel_assignment_period
        CHECK (
            effective_to IS NULL
            OR effective_to > effective_from
        )
);


-- ============================================================
-- 4. Remove Direct Fuel Type from Nozzle
--
-- V3 originally stored fuel_type_id directly on nozzle.
--
-- This is replaced by nozzle_fuel_type_assignment so that
-- nozzle fuel-type changes preserve history.
-- ============================================================

ALTER TABLE reconciliation.nozzle
    DROP CONSTRAINT fk_nozzle_fuel_type;


DROP INDEX IF EXISTS reconciliation.idx_nozzle_fuel_type;


ALTER TABLE reconciliation.nozzle
    DROP COLUMN fuel_type_id;


-- ============================================================
-- 5. Shift Definition
--
-- Configurable shift schedule for one fuel station.
--
-- Current EFS example:
--
--   Shift 1 / Day Shift
--       06:00 -> 18:00
--
--   Shift 2 / Night Shift
--       18:00 -> 06:00
--
-- If shift timings change later, previous definitions are
-- closed using effective_to and new definitions are created.
--
-- A shift crossing midnight is valid.
-- start_time and end_time must not be identical.
-- ============================================================

CREATE TABLE reconciliation.shift_definition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    fuel_station_id BIGINT NOT NULL,

    shift_number INTEGER NOT NULL,
    shift_name VARCHAR(100) NOT NULL,

    start_time TIME NOT NULL,
    end_time TIME NOT NULL,

    effective_from DATE NOT NULL,
    effective_to DATE,

    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ,
    updated_by BIGINT,

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_shift_definition_station
        FOREIGN KEY (fuel_station_id)
        REFERENCES reconciliation.fuel_station (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_shift_definition_station_number_from
        UNIQUE (
            fuel_station_id,
            shift_number,
            effective_from
        ),

    CONSTRAINT ck_shift_definition_number_positive
        CHECK (
            shift_number > 0
        ),

    CONSTRAINT ck_shift_definition_name_not_blank
        CHECK (
            BTRIM(shift_name) <> ''
        ),

    CONSTRAINT ck_shift_definition_times_different
        CHECK (
            start_time <> end_time
        ),

    CONSTRAINT ck_shift_definition_effective_period
        CHECK (
            effective_to IS NULL
            OR effective_to >= effective_from
        )
);


-- ============================================================
-- 6. Shift
--
-- Represents one actual occurrence of a configured shift.
--
-- Unlike the previous design, a shift belongs to the station
-- rather than directly to one dispenser unit.
--
-- The dispenser units that actually operate during the shift
-- are represented through shift_dispenser_unit.
--
-- Example:
--
--   Station       : EFS001
--   Business Date : 2026-08-14
--   Shift         : Day Shift
--   Actual Start  : 06:02
-- ============================================================

CREATE TABLE reconciliation.shift (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    fuel_station_id BIGINT NOT NULL,
    shift_definition_id BIGINT NOT NULL,

    business_date DATE NOT NULL,

    -- Snapshot of the configured shift number.
    shift_number INTEGER NOT NULL,

    started_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ,

    status VARCHAR(40) NOT NULL,

    reconciliation_tolerance NUMERIC(19, 2)
        NOT NULL DEFAULT 0,

    remarks VARCHAR(1000),

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,
    updated_at TIMESTAMPTZ,
    updated_by BIGINT,

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_shift_station
        FOREIGN KEY (fuel_station_id)
        REFERENCES reconciliation.fuel_station (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_shift_definition
        FOREIGN KEY (shift_definition_id)
        REFERENCES reconciliation.shift_definition (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_shift_station_business_date_number
        UNIQUE (
            fuel_station_id,
            business_date,
            shift_number
        ),

    CONSTRAINT ck_shift_number_positive
        CHECK (
            shift_number > 0
        ),

    CONSTRAINT ck_shift_tolerance_non_negative
        CHECK (
            reconciliation_tolerance >= 0
        ),

    CONSTRAINT ck_shift_time_period
        CHECK (
            ended_at IS NULL
            OR ended_at >= started_at
        )
);


-- ============================================================
-- 7. Shift Dispenser Unit
--
-- Represents a dispenser unit that actually became operational
-- during one shift.
--
-- A station may have three active physical DUs while only one
-- or two become operational during a particular shift.
--
-- No row is required for an available DU that was not operated.
--
-- Example:
--
--   Available:
--       DU-01
--       DU-02
--       DU-03
--
--   Operational tonight:
--       DU-01
--       DU-02
--
--   => two rows in shift_dispenser_unit.
-- ============================================================

CREATE TABLE reconciliation.shift_dispenser_unit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    shift_id BIGINT NOT NULL,
    dispenser_unit_id BIGINT NOT NULL,

    started_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_shift_dispenser_unit_shift
        FOREIGN KEY (shift_id)
        REFERENCES reconciliation.shift (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_shift_dispenser_unit_dispenser
        FOREIGN KEY (dispenser_unit_id)
        REFERENCES reconciliation.dispenser_unit (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_shift_dispenser_unit
        UNIQUE (
            shift_id,
            dispenser_unit_id
        ),

    CONSTRAINT ck_shift_dispenser_unit_period
        CHECK (
            ended_at IS NULL
            OR ended_at >= started_at
        )
);


-- ============================================================
-- 8. Shift Employee
--
-- Represents an employee participating in one actual shift.
--
-- Employee code and name are snapshotted so later changes to
-- employee master data do not change historical shift records.
--
-- This table records participation only.
-- Actual employee working time is stored separately in
-- employee_shift_hours.
-- ============================================================

CREATE TABLE reconciliation.shift_employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    shift_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,

    employee_code_snapshot VARCHAR(30) NOT NULL,
    employee_name_snapshot VARCHAR(150) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,

    CONSTRAINT fk_shift_employee_shift
        FOREIGN KEY (shift_id)
        REFERENCES reconciliation.shift (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_shift_employee_employee
        FOREIGN KEY (employee_id)
        REFERENCES reconciliation.employee (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_shift_employee
        UNIQUE (
            shift_id,
            employee_id
        ),

    CONSTRAINT ck_shift_employee_code_not_blank
        CHECK (
            BTRIM(employee_code_snapshot) <> ''
        ),

    CONSTRAINT ck_shift_employee_name_not_blank
        CHECK (
            BTRIM(employee_name_snapshot) <> ''
        )
);


-- ============================================================
-- 9. Employee Shift Hours
--
-- Records the employee's actual working period.
--
-- Actual employee hours are independent from the configured
-- station shift duration.
--
-- Example:
--
--   Configured shift:
--       06:00 -> 18:00
--
--   Employee actual work:
--       06:07 -> 17:55
--
-- total_duration_minutes is calculated by the backend.
-- The browser must not supply the authoritative duration.
--
-- Initial implementation assumption:
--   One continuous work period per employee per shift.
-- ============================================================

CREATE TABLE reconciliation.employee_shift_hours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    shift_id BIGINT NOT NULL,
    shift_employee_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,

    started_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ,

    total_duration_minutes INTEGER,

    status VARCHAR(20) NOT NULL,

    remarks VARCHAR(1000),

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,
    updated_at TIMESTAMPTZ,
    updated_by BIGINT,

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_employee_shift_hours_shift
        FOREIGN KEY (shift_id)
        REFERENCES reconciliation.shift (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_employee_shift_hours_shift_employee
        FOREIGN KEY (shift_employee_id)
        REFERENCES reconciliation.shift_employee (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_employee_shift_hours_employee
        FOREIGN KEY (employee_id)
        REFERENCES reconciliation.employee (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_employee_shift_hours_shift_employee
        UNIQUE (
            shift_id,
            employee_id
        ),

    CONSTRAINT ck_employee_shift_hours_period
        CHECK (
            ended_at IS NULL
            OR ended_at >= started_at
        ),

    CONSTRAINT ck_employee_shift_hours_duration
        CHECK (
            total_duration_minutes IS NULL
            OR total_duration_minutes >= 0
        ),

    CONSTRAINT ck_employee_shift_hours_status
        CHECK (
            status IN (
                'STARTED',
                'COMPLETED',
                'CORRECTED'
            )
        )
);


-- ============================================================
-- 10. Employee Shift Hours Correction
--
-- Append-only history of authorized corrections to completed
-- employee working-time records.
--
-- Corrections must preserve previous and corrected values,
-- reason, user and timestamp.
-- ============================================================

CREATE TABLE reconciliation.employee_shift_hours_correction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    employee_shift_hours_id BIGINT NOT NULL,

    previous_started_at TIMESTAMPTZ NOT NULL,
    previous_ended_at TIMESTAMPTZ,

    corrected_started_at TIMESTAMPTZ NOT NULL,
    corrected_ended_at TIMESTAMPTZ,

    previous_duration_minutes INTEGER,
    corrected_duration_minutes INTEGER,

    correction_reason VARCHAR(1000) NOT NULL,

    corrected_by BIGINT NOT NULL,
    corrected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_employee_shift_hours_correction_record
        FOREIGN KEY (employee_shift_hours_id)
        REFERENCES reconciliation.employee_shift_hours (id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_employee_shift_hours_corrected_period
        CHECK (
            corrected_ended_at IS NULL
            OR corrected_ended_at >= corrected_started_at
        ),

    CONSTRAINT ck_employee_shift_hours_previous_duration
        CHECK (
            previous_duration_minutes IS NULL
            OR previous_duration_minutes >= 0
        ),

    CONSTRAINT ck_employee_shift_hours_corrected_duration
        CHECK (
            corrected_duration_minutes IS NULL
            OR corrected_duration_minutes >= 0
        ),

    CONSTRAINT ck_employee_shift_hours_correction_reason
        CHECK (
            BTRIM(correction_reason) <> ''
        )
);


-- ============================================================
-- 11. Shift Nozzle Assignment
--
-- Stores the exact historical nozzle assignment used by an
-- employee during one shift.
--
-- Typical workflow:
--
--   Manager selects:
--       Employee
--       DU
--       Side
--
--   Application resolves:
--       all configured nozzles belonging to that side
--       and each nozzle's currently effective fuel type
--
--   Application creates one shift_nozzle_assignment row
--   for each nozzle.
--
-- Example:
--
--   DU-01
--   Side A
--   Employee = Sujith
--
--   N1 -> PETROL
--   N2 -> PETROL
--
-- creates two assignment rows.
--
-- Multiple historical rows for the same nozzle during one
-- shift are allowed so employee replacement can be preserved.
--
-- Example:
--
--   N1 -> Employee A 06:00 -> 12:00
--   N1 -> Employee B 12:00 -> 18:00
--
-- Overlapping assignment periods will initially be prevented
-- by application-level transactional validation.
-- ============================================================

CREATE TABLE reconciliation.shift_nozzle_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    shift_id BIGINT NOT NULL,

    shift_dispenser_unit_id BIGINT NOT NULL,
    dispenser_side_id BIGINT NOT NULL,

    shift_employee_id BIGINT NOT NULL,

    nozzle_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,

    fuel_type_id BIGINT NOT NULL,

    -- Historical snapshots
    nozzle_number_snapshot INTEGER NOT NULL,
    fuel_type_code_snapshot VARCHAR(30) NOT NULL,

    assigned_at TIMESTAMPTZ NOT NULL,
    released_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,

    CONSTRAINT fk_shift_nozzle_assignment_shift
        FOREIGN KEY (shift_id)
        REFERENCES reconciliation.shift (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_shift_nozzle_assignment_shift_du
        FOREIGN KEY (shift_dispenser_unit_id)
        REFERENCES reconciliation.shift_dispenser_unit (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_shift_nozzle_assignment_side
        FOREIGN KEY (dispenser_side_id)
        REFERENCES reconciliation.dispenser_side (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_shift_nozzle_assignment_shift_employee
        FOREIGN KEY (shift_employee_id)
        REFERENCES reconciliation.shift_employee (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_shift_nozzle_assignment_nozzle
        FOREIGN KEY (nozzle_id)
        REFERENCES reconciliation.nozzle (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_shift_nozzle_assignment_employee
        FOREIGN KEY (employee_id)
        REFERENCES reconciliation.employee (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_shift_nozzle_assignment_fuel_type
        FOREIGN KEY (fuel_type_id)
        REFERENCES reconciliation.fuel_type (id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_shift_nozzle_assignment_number_positive
        CHECK (
            nozzle_number_snapshot > 0
        ),

    CONSTRAINT ck_shift_nozzle_assignment_fuel_code_not_blank
        CHECK (
            BTRIM(fuel_type_code_snapshot) <> ''
        ),

    CONSTRAINT ck_shift_nozzle_assignment_period
        CHECK (
            released_at IS NULL
            OR released_at >= assigned_at
        )
);


-- ============================================================
-- 12. Indexes
-- ============================================================


-- Dispenser Side
-- ============================================================

CREATE INDEX idx_dispenser_side_unit_active
    ON reconciliation.dispenser_side (
        dispenser_unit_id,
        active
    );


-- Nozzle / Fuel-Type Configuration
-- ============================================================

CREATE INDEX idx_nozzle_side
    ON reconciliation.nozzle (
        dispenser_side_id
    );


CREATE INDEX idx_nozzle_fuel_assignment_nozzle_dates
    ON reconciliation.nozzle_fuel_type_assignment (
        nozzle_id,
        effective_from,
        effective_to
    );


CREATE INDEX idx_nozzle_fuel_assignment_fuel_type
    ON reconciliation.nozzle_fuel_type_assignment (
        fuel_type_id
    );


-- Shift Definition
-- ============================================================

CREATE INDEX idx_shift_definition_station_dates
    ON reconciliation.shift_definition (
        fuel_station_id,
        effective_from,
        effective_to
    );


-- Shift
-- ============================================================

CREATE INDEX idx_shift_station_business_date
    ON reconciliation.shift (
        fuel_station_id,
        business_date
    );


CREATE INDEX idx_shift_status
    ON reconciliation.shift (
        status
    );


CREATE INDEX idx_shift_created_by
    ON reconciliation.shift (
        created_by
    );


-- Shift Dispenser Unit
-- ============================================================

CREATE INDEX idx_shift_dispenser_unit_shift
    ON reconciliation.shift_dispenser_unit (
        shift_id
    );


CREATE INDEX idx_shift_dispenser_unit_dispenser
    ON reconciliation.shift_dispenser_unit (
        dispenser_unit_id
    );


-- Shift Employee
-- ============================================================

CREATE INDEX idx_shift_employee_shift
    ON reconciliation.shift_employee (
        shift_id
    );


CREATE INDEX idx_shift_employee_employee
    ON reconciliation.shift_employee (
        employee_id
    );


-- Employee Shift Hours
-- ============================================================

CREATE INDEX idx_employee_shift_hours_shift
    ON reconciliation.employee_shift_hours (
        shift_id
    );


CREATE INDEX idx_employee_shift_hours_employee
    ON reconciliation.employee_shift_hours (
        employee_id
    );


CREATE INDEX idx_employee_shift_hours_started_at
    ON reconciliation.employee_shift_hours (
        started_at
    );


CREATE INDEX idx_employee_shift_hours_status
    ON reconciliation.employee_shift_hours (
        status
    );


-- Employee Shift Hours Corrections
-- ============================================================

CREATE INDEX idx_employee_shift_hours_correction_record
    ON reconciliation.employee_shift_hours_correction (
        employee_shift_hours_id
    );


CREATE INDEX idx_employee_shift_hours_correction_corrected_at
    ON reconciliation.employee_shift_hours_correction (
        corrected_at
    );


-- Shift Nozzle Assignments
-- ============================================================

CREATE INDEX idx_shift_nozzle_assignment_shift
    ON reconciliation.shift_nozzle_assignment (
        shift_id
    );


CREATE INDEX idx_shift_nozzle_assignment_shift_du
    ON reconciliation.shift_nozzle_assignment (
        shift_dispenser_unit_id
    );


CREATE INDEX idx_shift_nozzle_assignment_side
    ON reconciliation.shift_nozzle_assignment (
        dispenser_side_id
    );


CREATE INDEX idx_shift_nozzle_assignment_employee
    ON reconciliation.shift_nozzle_assignment (
        employee_id
    );


CREATE INDEX idx_shift_nozzle_assignment_nozzle
    ON reconciliation.shift_nozzle_assignment (
        nozzle_id
    );