-- ============================================================
-- Fuel Station Shift Reconciliation System
-- Database Migration V7
--
-- Purpose:
--   1. Create employee-owned START/END receipt records.
--   2. Preserve receipt replacement history.
--   3. Store all nozzle readings printed on each receipt.
--   4. Preserve multiple OCR processing attempts.
--   5. Preserve field-level OCR evidence.
--   6. Preserve append-only manual correction history.
--
-- Important operational rules:
--
--   - One employee uploads one START receipt and one END receipt
--     for their participation in a shift.
--
--   - The physical DU receipt contains readings for all nozzles
--     printed by that DU, even though the employee operates only
--     the nozzles assigned to their dispenser side.
--
--   - OCR therefore preserves all printed nozzle readings.
--
--   - Later reconciliation selects only the readings belonging
--     to that employee through shift_nozzle_assignment.
--
--   - Confirmed START receipt datetime will be used by the
--     application as employee_shift_hours.started_at.
--
--   - Confirmed END receipt datetime will be used by the
--     application as employee_shift_hours.ended_at.
--
--   - Upload time is not the authoritative employee work time.
--
--   - Raw OCR datetime must not update working hours until the
--     receipt has been validated and confirmed.
-- ============================================================


-- ============================================================
-- 1. Receipt
--
-- Represents one uploaded START or END receipt belonging to one
-- employee's participation in one operational shift.
--
-- The record also keeps explicit DU and dispenser-side context.
--
-- Replacement receipts are preserved historically.
-- Only one active START receipt and one active END receipt may
-- exist for one shift_employee.
-- ============================================================

CREATE TABLE reconciliation.receipt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    shift_id BIGINT NOT NULL,
    shift_employee_id BIGINT NOT NULL,
    shift_dispenser_unit_id BIGINT NOT NULL,
    dispenser_side_id BIGINT NOT NULL,

    receipt_type VARCHAR(20) NOT NULL,

    -- Values extracted/confirmed from the printed receipt
    du_serial_number VARCHAR(100),
    normalized_du_serial_number VARCHAR(100),
    receipt_datetime TIMESTAMPTZ,

    -- Original uploaded file information
    original_filename VARCHAR(255) NOT NULL,

    -- Application-generated physical storage filename
    stored_filename VARCHAR(255) NOT NULL,

    storage_path VARCHAR(1000) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL,

    sha256_hash CHAR(64) NOT NULL,

    image_width INTEGER,
    image_height INTEGER,

    -- Summary OCR information
    ocr_raw_text TEXT,
    ocr_confidence NUMERIC(5, 2),

    processing_status VARCHAR(40) NOT NULL,

    manual_correction_applied BOOLEAN NOT NULL DEFAULT FALSE,

    uploaded_by BIGINT NOT NULL,
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    confirmed_by BIGINT,
    confirmed_at TIMESTAMPTZ,

    -- Replacement history
    active BOOLEAN NOT NULL DEFAULT TRUE,
    replaced_receipt_id BIGINT,
    replacement_reason VARCHAR(1000),

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_receipt_shift
        FOREIGN KEY (shift_id)
        REFERENCES reconciliation.shift (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_receipt_shift_employee
        FOREIGN KEY (shift_employee_id)
        REFERENCES reconciliation.shift_employee (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_receipt_shift_dispenser_unit
        FOREIGN KEY (shift_dispenser_unit_id)
        REFERENCES reconciliation.shift_dispenser_unit (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_receipt_dispenser_side
        FOREIGN KEY (dispenser_side_id)
        REFERENCES reconciliation.dispenser_side (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_receipt_uploaded_by
        FOREIGN KEY (uploaded_by)
        REFERENCES reconciliation.application_user (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_receipt_confirmed_by
        FOREIGN KEY (confirmed_by)
        REFERENCES reconciliation.application_user (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_receipt_replaced_receipt
        FOREIGN KEY (replaced_receipt_id)
        REFERENCES reconciliation.receipt (id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_receipt_type
        CHECK (
            receipt_type IN (
                'START',
                'END'
            )
        ),

    CONSTRAINT ck_receipt_original_filename_not_blank
        CHECK (
            BTRIM(original_filename) <> ''
        ),

    CONSTRAINT ck_receipt_stored_filename_not_blank
        CHECK (
            BTRIM(stored_filename) <> ''
        ),

    CONSTRAINT ck_receipt_storage_path_not_blank
        CHECK (
            BTRIM(storage_path) <> ''
        ),

    CONSTRAINT ck_receipt_content_type_not_blank
        CHECK (
            BTRIM(content_type) <> ''
        ),

    CONSTRAINT ck_receipt_file_size_positive
        CHECK (
            file_size > 0
        ),

    CONSTRAINT ck_receipt_hash_not_blank
        CHECK (
            BTRIM(sha256_hash) <> ''
        ),

    CONSTRAINT ck_receipt_image_width_positive
        CHECK (
            image_width IS NULL
            OR image_width > 0
        ),

    CONSTRAINT ck_receipt_image_height_positive
        CHECK (
            image_height IS NULL
            OR image_height > 0
        ),

    CONSTRAINT ck_receipt_ocr_confidence
        CHECK (
            ocr_confidence IS NULL
            OR (
                ocr_confidence >= 0
                AND ocr_confidence <= 100
            )
        ),

    CONSTRAINT ck_receipt_processing_status
        CHECK (
            processing_status IN (
                'UPLOADED',
                'VALIDATING_IMAGE',
                'IMAGE_VALIDATED',
                'PREPROCESSING',
                'OCR_IN_PROGRESS',
                'OCR_COMPLETED',
                'PARSING',
                'PARSED',
                'REVIEW_REQUIRED',
                'CONFIRMED',
                'FAILED',
                'REJECTED'
            )
        ),

    CONSTRAINT ck_receipt_replacement_reason
        CHECK (
            replacement_reason IS NULL
            OR BTRIM(replacement_reason) <> ''
        ),

    CONSTRAINT ck_receipt_confirmation
        CHECK (
            (
                confirmed_by IS NULL
                AND confirmed_at IS NULL
            )
            OR
            (
                confirmed_by IS NOT NULL
                AND confirmed_at IS NOT NULL
            )
        )
);


-- ============================================================
-- Only one CURRENT/ACTIVE START receipt and one CURRENT/ACTIVE
-- END receipt may exist for one shift employee.
--
-- Historical replaced receipts remain in the table with
-- active = FALSE.
-- ============================================================

CREATE UNIQUE INDEX uk_receipt_active_employee_type
    ON reconciliation.receipt (
        shift_employee_id,
        receipt_type
    )
    WHERE active = TRUE;


-- ============================================================
-- 2. Receipt Nozzle Reading
--
-- Stores one printed nozzle's values from one receipt.
--
-- IMPORTANT:
--   All nozzle readings printed by the DU are preserved.
--
-- Example:
--
--   Employee assigned Side A -> N1 + N2
--
--   Receipt contains:
--       N1
--       N2
--       N3
--       N4
--
--   All four rows are stored.
--
--   Later reconciliation uses shift_nozzle_assignment to select
--   only N1 + N2 for this employee.
--
-- nozzle_id is nullable because OCR parsing may identify the
-- printed nozzle number before the configured nozzle master
-- record is successfully resolved.
-- ============================================================

CREATE TABLE reconciliation.receipt_nozzle_reading (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    receipt_id BIGINT NOT NULL,

    nozzle_id BIGINT,

    nozzle_number INTEGER NOT NULL,

    atot NUMERIC(19, 2) NOT NULL,
    vtot NUMERIC(19, 3) NOT NULL,
    ecal_factor NUMERIC(12, 6),

    -- Original recognized OCR strings
    atot_ocr_text VARCHAR(100),
    vtot_ocr_text VARCHAR(100),
    ecal_ocr_text VARCHAR(100),

    atot_confidence NUMERIC(5, 2),
    vtot_confidence NUMERIC(5, 2),
    ecal_confidence NUMERIC(5, 2),

    manually_corrected BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,

    updated_at TIMESTAMPTZ,
    updated_by BIGINT,

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_receipt_nozzle_reading_receipt
        FOREIGN KEY (receipt_id)
        REFERENCES reconciliation.receipt (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_receipt_nozzle_reading_nozzle
        FOREIGN KEY (nozzle_id)
        REFERENCES reconciliation.nozzle (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_receipt_nozzle_reading_created_by
        FOREIGN KEY (created_by)
        REFERENCES reconciliation.application_user (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_receipt_nozzle_reading_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES reconciliation.application_user (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_receipt_nozzle_reading
        UNIQUE (
            receipt_id,
            nozzle_number
        ),

    CONSTRAINT ck_receipt_nozzle_number_positive
        CHECK (
            nozzle_number > 0
        ),

    CONSTRAINT ck_receipt_nozzle_atot_non_negative
        CHECK (
            atot >= 0
        ),

    CONSTRAINT ck_receipt_nozzle_vtot_non_negative
        CHECK (
            vtot >= 0
        ),

    CONSTRAINT ck_receipt_nozzle_atot_confidence
        CHECK (
            atot_confidence IS NULL
            OR (
                atot_confidence >= 0
                AND atot_confidence <= 100
            )
        ),

    CONSTRAINT ck_receipt_nozzle_vtot_confidence
        CHECK (
            vtot_confidence IS NULL
            OR (
                vtot_confidence >= 0
                AND vtot_confidence <= 100
            )
        ),

    CONSTRAINT ck_receipt_nozzle_ecal_confidence
        CHECK (
            ecal_confidence IS NULL
            OR (
                ecal_confidence >= 0
                AND ecal_confidence <= 100
            )
        )
);


-- ============================================================
-- 3. OCR Processing Attempt
--
-- Stores every OCR execution attempt for one receipt.
--
-- Multiple attempts are preserved.
--
-- Example:
--
--   Attempt 1 -> DEFAULT
--   Attempt 2 -> HIGH_CONTRAST
--   Attempt 3 -> DESKEW
--
-- Previous attempts are never overwritten.
-- ============================================================

CREATE TABLE reconciliation.ocr_processing_attempt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    receipt_id BIGINT NOT NULL,

    attempt_number INTEGER NOT NULL,

    preprocessing_profile VARCHAR(100),

    raw_text TEXT,

    average_confidence NUMERIC(5, 2),

    processing_duration_ms BIGINT,

    successful BOOLEAN NOT NULL DEFAULT FALSE,

    error_message TEXT,

    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,

    CONSTRAINT fk_ocr_processing_attempt_receipt
        FOREIGN KEY (receipt_id)
        REFERENCES reconciliation.receipt (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_ocr_processing_attempt
        UNIQUE (
            receipt_id,
            attempt_number
        ),

    CONSTRAINT ck_ocr_processing_attempt_number_positive
        CHECK (
            attempt_number > 0
        ),

    CONSTRAINT ck_ocr_processing_average_confidence
        CHECK (
            average_confidence IS NULL
            OR (
                average_confidence >= 0
                AND average_confidence <= 100
            )
        ),

    CONSTRAINT ck_ocr_processing_duration_non_negative
        CHECK (
            processing_duration_ms IS NULL
            OR processing_duration_ms >= 0
        ),

    CONSTRAINT ck_ocr_processing_period
        CHECK (
            completed_at IS NULL
            OR completed_at >= started_at
        )
);


-- ============================================================
-- 4. OCR Field Result
--
-- Stores field-level OCR evidence for one OCR attempt.
--
-- Example fields:
--
--   DU_SERIAL_NUMBER
--   RECEIPT_DATETIME
--   ATOT
--   VTOT
--   ECAL
--
-- nozzle_number is optional because some fields belong to the
-- receipt header rather than a particular nozzle.
-- ============================================================

CREATE TABLE reconciliation.ocr_field_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    ocr_processing_attempt_id BIGINT NOT NULL,

    field_name VARCHAR(100) NOT NULL,

    nozzle_number INTEGER,

    recognized_text VARCHAR(500),
    normalized_text VARCHAR(500),

    confidence NUMERIC(5, 2),

    bounding_x INTEGER,
    bounding_y INTEGER,
    bounding_width INTEGER,
    bounding_height INTEGER,

    warning_message VARCHAR(1000),

    CONSTRAINT fk_ocr_field_result_attempt
        FOREIGN KEY (ocr_processing_attempt_id)
        REFERENCES reconciliation.ocr_processing_attempt (id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_ocr_field_name_not_blank
        CHECK (
            BTRIM(field_name) <> ''
        ),

    CONSTRAINT ck_ocr_field_nozzle_number
        CHECK (
            nozzle_number IS NULL
            OR nozzle_number > 0
        ),

    CONSTRAINT ck_ocr_field_confidence
        CHECK (
            confidence IS NULL
            OR (
                confidence >= 0
                AND confidence <= 100
            )
        ),

    CONSTRAINT ck_ocr_field_bounding_width
        CHECK (
            bounding_width IS NULL
            OR bounding_width >= 0
        ),

    CONSTRAINT ck_ocr_field_bounding_height
        CHECK (
            bounding_height IS NULL
            OR bounding_height >= 0
        )
);


-- ============================================================
-- 5. Manual Correction
--
-- Append-only correction history.
--
-- Original OCR/extracted information must never disappear when
-- the user corrects a value.
--
-- Example:
--
--   field_name      = VTOT
--   original_value  = 12458.885
--   corrected_value = 12458.865
--   reason          = OCR digit misread
--
-- This table must not be updated or deleted through normal
-- application operations.
-- ============================================================

CREATE TABLE reconciliation.manual_correction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    receipt_id BIGINT NOT NULL,

    receipt_nozzle_reading_id BIGINT,

    field_name VARCHAR(100) NOT NULL,

    original_value VARCHAR(500),
    corrected_value VARCHAR(500) NOT NULL,

    reason VARCHAR(1000) NOT NULL,

    corrected_by BIGINT NOT NULL,
    corrected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_manual_correction_receipt
        FOREIGN KEY (receipt_id)
        REFERENCES reconciliation.receipt (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_manual_correction_reading
        FOREIGN KEY (receipt_nozzle_reading_id)
        REFERENCES reconciliation.receipt_nozzle_reading (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_manual_correction_corrected_by
        FOREIGN KEY (corrected_by)
        REFERENCES reconciliation.application_user (id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_manual_correction_field_name_not_blank
        CHECK (
            BTRIM(field_name) <> ''
        ),

    CONSTRAINT ck_manual_correction_corrected_value_not_blank
        CHECK (
            BTRIM(corrected_value) <> ''
        ),

    CONSTRAINT ck_manual_correction_reason_not_blank
        CHECK (
            BTRIM(reason) <> ''
        )
);


-- ============================================================
-- 6. Indexes
-- ============================================================


-- Receipt
-- ============================================================

CREATE INDEX idx_receipt_shift_employee
    ON reconciliation.receipt (
        shift_employee_id
    );


CREATE INDEX idx_receipt_shift
    ON reconciliation.receipt (
        shift_id
    );


CREATE INDEX idx_receipt_shift_dispenser_unit
    ON reconciliation.receipt (
        shift_dispenser_unit_id
    );


CREATE INDEX idx_receipt_dispenser_side
    ON reconciliation.receipt (
        dispenser_side_id
    );


CREATE INDEX idx_receipt_hash
    ON reconciliation.receipt (
        sha256_hash
    );


CREATE INDEX idx_receipt_du_serial
    ON reconciliation.receipt (
        normalized_du_serial_number
    );


CREATE INDEX idx_receipt_processing_status
    ON reconciliation.receipt (
        processing_status
    );


CREATE INDEX idx_receipt_uploaded_at
    ON reconciliation.receipt (
        uploaded_at
    );


CREATE INDEX idx_receipt_datetime
    ON reconciliation.receipt (
        receipt_datetime
    );


-- Receipt Nozzle Reading
-- ============================================================

CREATE INDEX idx_receipt_nozzle_reading_receipt
    ON reconciliation.receipt_nozzle_reading (
        receipt_id
    );


CREATE INDEX idx_receipt_nozzle_reading_nozzle
    ON reconciliation.receipt_nozzle_reading (
        nozzle_id
    );


-- OCR Processing Attempt
-- ============================================================

CREATE INDEX idx_ocr_processing_attempt_receipt
    ON reconciliation.ocr_processing_attempt (
        receipt_id
    );


CREATE INDEX idx_ocr_processing_attempt_started_at
    ON reconciliation.ocr_processing_attempt (
        started_at
    );


-- OCR Field Result
-- ============================================================

CREATE INDEX idx_ocr_field_result_attempt
    ON reconciliation.ocr_field_result (
        ocr_processing_attempt_id
    );


CREATE INDEX idx_ocr_field_result_field_name
    ON reconciliation.ocr_field_result (
        field_name
    );


CREATE INDEX idx_ocr_field_result_confidence
    ON reconciliation.ocr_field_result (
        confidence
    );


-- Manual Correction
-- ============================================================

CREATE INDEX idx_manual_correction_receipt
    ON reconciliation.manual_correction (
        receipt_id
    );


CREATE INDEX idx_manual_correction_reading
    ON reconciliation.manual_correction (
        receipt_nozzle_reading_id
    );


CREATE INDEX idx_manual_correction_corrected_at
    ON reconciliation.manual_correction (
        corrected_at
    );