-- ============================================================
-- Fuel Station Shift Reconciliation System
-- Database Migration V8
--
-- Purpose:
--   1. Create nozzle-wise fuel-sale calculation records.
--   2. Create employee cash-denomination entries.
--   3. Create consolidated employee coins entries.
--   4. Create consolidated TID-device collection entries.
--   5. Create customer credit-sale records.
--   6. Create expense and adjustment records.
--
-- Important business rules:
--
--   Fuel quantity:
--       Quantity Sold = End VTOT - Start VTOT
--
--   Fuel sales:
--       Calculated Sales Amount =
--           Quantity Sold x applicable Price Per Litre
--
--   Price Per Litre:
--       Resolved from fuel_price for the station/fuel/time
--       and snapshotted into fuel_sale.
--
--   ATOT:
--       Preserved in receipt data but NOT used in current
--       sales/reconciliation calculations.
--
--   Cash:
--       Total Notes Amount =
--           SUM(cash_denomination_entry.calculated_amount)
--
--       Cash Total =
--           Total Notes Amount + coins_entry.amount
--
--   TID:
--       One consolidated device total per employee per shift.
--       It represents UPI + debit-card + credit-card collections.
--
--   Total Collections:
--       Cash Total
--       + TID Device Total
--       + Credit Sale Total (when applicable)
--
--   Difference Amount:
--       Total Collections - Calculated Sales Amount
--
--   Reconciliation totals themselves will be created in a
--   later migration.
-- ============================================================


-- ============================================================
-- 1. Fuel Sale
--
-- One calculated sales record for one historical
-- shift-nozzle assignment.
--
-- The exact employee/nozzle/fuel-type context comes from
-- shift_nozzle_assignment.
--
-- price_per_litre is resolved from fuel_price and snapshotted
-- here so historical calculations remain reproducible even
-- after fuel-price master data changes.
-- ============================================================

CREATE TABLE reconciliation.fuel_sale (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    shift_id BIGINT NOT NULL,
    shift_nozzle_assignment_id BIGINT NOT NULL,

    employee_id BIGINT NOT NULL,
    nozzle_id BIGINT NOT NULL,
    fuel_type_id BIGINT NOT NULL,

    start_receipt_reading_id BIGINT NOT NULL,
    end_receipt_reading_id BIGINT NOT NULL,

    start_vtot NUMERIC(19, 3) NOT NULL,
    end_vtot NUMERIC(19, 3) NOT NULL,

    quantity_sold NUMERIC(19, 3) NOT NULL,

    fuel_price_id BIGINT NOT NULL,
    price_per_litre NUMERIC(12, 3) NOT NULL,

    calculated_sales_amount NUMERIC(19, 2) NOT NULL,

    calculated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    calculation_version INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT fk_fuel_sale_shift
        FOREIGN KEY (shift_id)
        REFERENCES reconciliation.shift (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_fuel_sale_shift_nozzle_assignment
        FOREIGN KEY (shift_nozzle_assignment_id)
        REFERENCES reconciliation.shift_nozzle_assignment (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_fuel_sale_employee
        FOREIGN KEY (employee_id)
        REFERENCES reconciliation.employee (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_fuel_sale_nozzle
        FOREIGN KEY (nozzle_id)
        REFERENCES reconciliation.nozzle (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_fuel_sale_fuel_type
        FOREIGN KEY (fuel_type_id)
        REFERENCES reconciliation.fuel_type (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_fuel_sale_start_reading
        FOREIGN KEY (start_receipt_reading_id)
        REFERENCES reconciliation.receipt_nozzle_reading (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_fuel_sale_end_reading
        FOREIGN KEY (end_receipt_reading_id)
        REFERENCES reconciliation.receipt_nozzle_reading (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_fuel_sale_fuel_price
        FOREIGN KEY (fuel_price_id)
        REFERENCES reconciliation.fuel_price (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_fuel_sale_assignment_version
        UNIQUE (
            shift_nozzle_assignment_id,
            calculation_version
        ),

    CONSTRAINT ck_fuel_sale_end_vtot
        CHECK (
            end_vtot >= start_vtot
        ),

    CONSTRAINT ck_fuel_sale_quantity_non_negative
        CHECK (
            quantity_sold >= 0
        ),

    CONSTRAINT ck_fuel_sale_price_positive
        CHECK (
            price_per_litre > 0
        ),

    CONSTRAINT ck_fuel_sale_amount_non_negative
        CHECK (
            calculated_sales_amount >= 0
        ),

    CONSTRAINT ck_fuel_sale_calculation_version
        CHECK (
            calculation_version > 0
        )
);


-- ============================================================
-- 2. Cash Denomination Entry
--
-- Stores note quantity for one denomination for one employee
-- within one shift.
--
-- calculated_amount must be calculated by the backend:
--
--     denomination_value_snapshot x quantity
--
-- The browser must not supply the authoritative calculated
-- amount.
-- ============================================================

CREATE TABLE reconciliation.cash_denomination_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    shift_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,

    cash_denomination_id BIGINT NOT NULL,

    denomination_value_snapshot NUMERIC(12, 2) NOT NULL,

    quantity INTEGER NOT NULL,

    calculated_amount NUMERIC(19, 2) NOT NULL,

    entered_by BIGINT NOT NULL,
    entered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ,
    updated_by BIGINT,

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_cash_denomination_entry_shift
        FOREIGN KEY (shift_id)
        REFERENCES reconciliation.shift (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_cash_denomination_entry_employee
        FOREIGN KEY (employee_id)
        REFERENCES reconciliation.employee (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_cash_denomination_entry_denomination
        FOREIGN KEY (cash_denomination_id)
        REFERENCES reconciliation.cash_denomination (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_cash_denomination_entry_entered_by
        FOREIGN KEY (entered_by)
        REFERENCES reconciliation.application_user (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_cash_denomination_entry_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES reconciliation.application_user (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_cash_denomination_entry
        UNIQUE (
            shift_id,
            employee_id,
            cash_denomination_id
        ),

    CONSTRAINT ck_cash_denomination_entry_snapshot_positive
        CHECK (
            denomination_value_snapshot > 0
        ),

    CONSTRAINT ck_cash_denomination_entry_quantity
        CHECK (
            quantity >= 0
        ),

    CONSTRAINT ck_cash_denomination_entry_amount
        CHECK (
            calculated_amount >= 0
        )
);


-- ============================================================
-- 3. Coins Entry
--
-- Stores one consolidated Coins Amount for one employee
-- within one shift.
--
-- Individual coin denomination quantities are not maintained.
-- ============================================================

CREATE TABLE reconciliation.coins_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    shift_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,

    amount NUMERIC(14, 2) NOT NULL,

    entered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    entered_by BIGINT NOT NULL,

    updated_at TIMESTAMPTZ,
    updated_by BIGINT,

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_coins_entry_shift
        FOREIGN KEY (shift_id)
        REFERENCES reconciliation.shift (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_coins_entry_employee
        FOREIGN KEY (employee_id)
        REFERENCES reconciliation.employee (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_coins_entry_entered_by
        FOREIGN KEY (entered_by)
        REFERENCES reconciliation.application_user (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_coins_entry_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES reconciliation.application_user (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_coins_entry_shift_employee
        UNIQUE (
            shift_id,
            employee_id
        ),

    CONSTRAINT ck_coins_entry_amount_non_negative
        CHECK (
            amount >= 0
        )
);


-- ============================================================
-- 4. TID Collection
--
-- Stores one consolidated TID-device collection total for one
-- employee within one shift.
--
-- The amount represents the combined total received through
-- that TID device:
--
--     UPI
--     + Debit Card
--     + Credit Card
--
-- Example:
--
--     TID: TID12345       12,500.00
--
-- One TID/device total is maintained per employee per shift.
-- ============================================================

CREATE TABLE reconciliation.tid_collection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    shift_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,

    terminal_identifier VARCHAR(100) NOT NULL,

    amount NUMERIC(19, 2) NOT NULL,

    entered_by BIGINT NOT NULL,
    entered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ,
    updated_by BIGINT,

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_tid_collection_shift
        FOREIGN KEY (shift_id)
        REFERENCES reconciliation.shift (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_tid_collection_employee
        FOREIGN KEY (employee_id)
        REFERENCES reconciliation.employee (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_tid_collection_entered_by
        FOREIGN KEY (entered_by)
        REFERENCES reconciliation.application_user (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_tid_collection_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES reconciliation.application_user (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_tid_collection_shift_employee
        UNIQUE (
            shift_id,
            employee_id
        ),

    CONSTRAINT ck_tid_collection_terminal_not_blank
        CHECK (
            BTRIM(terminal_identifier) <> ''
        ),

    CONSTRAINT ck_tid_collection_amount_non_negative
        CHECK (
            amount >= 0
        )
);


-- ============================================================
-- 5. Credit Sale
--
-- Represents fuel supplied to a customer on account/credit
-- for later settlement.
--
-- IMPORTANT:
--   This is NOT a credit-card transaction.
--
-- Credit-card payments are already included in tid_collection.
-- ============================================================

CREATE TABLE reconciliation.credit_sale (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    shift_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,

    customer_name VARCHAR(200) NOT NULL,
    customer_reference VARCHAR(150),

    vehicle_number VARCHAR(50),

    amount NUMERIC(19, 2) NOT NULL,

    remarks VARCHAR(1000),

    entered_by BIGINT NOT NULL,
    entered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    settlement_status VARCHAR(30) NOT NULL
        DEFAULT 'OUTSTANDING',

    settled_at TIMESTAMPTZ,

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_credit_sale_shift
        FOREIGN KEY (shift_id)
        REFERENCES reconciliation.shift (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_credit_sale_employee
        FOREIGN KEY (employee_id)
        REFERENCES reconciliation.employee (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_credit_sale_entered_by
        FOREIGN KEY (entered_by)
        REFERENCES reconciliation.application_user (id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_credit_sale_customer_not_blank
        CHECK (
            BTRIM(customer_name) <> ''
        ),

    CONSTRAINT ck_credit_sale_amount_positive
        CHECK (
            amount > 0
        ),

    CONSTRAINT ck_credit_sale_settlement_status
        CHECK (
            settlement_status IN (
                'OUTSTANDING',
                'PARTIALLY_SETTLED',
                'SETTLED',
                'CANCELLED'
            )
        ),

    CONSTRAINT ck_credit_sale_settled_at
        CHECK (
            settlement_status <> 'SETTLED'
            OR settled_at IS NOT NULL
        )
);


-- ============================================================
-- 6. Adjustment
--
-- Stores expenses and other authorized adjustments.
--
-- Amount is always stored as a positive value.
--
-- Its effect on reconciliation is determined by direction.
--
-- Example:
--
--     EXPENSE
--     amount = 350.00
--     direction = DEDUCT_FROM_ACCOUNTED_AMOUNT
-- ============================================================

CREATE TABLE reconciliation.adjustment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    shift_id BIGINT NOT NULL,

    employee_id BIGINT,

    adjustment_type VARCHAR(40) NOT NULL,

    direction VARCHAR(40) NOT NULL,

    amount NUMERIC(19, 2) NOT NULL,

    description VARCHAR(1000) NOT NULL,

    reference_number VARCHAR(150),

    approval_status VARCHAR(30) NOT NULL
        DEFAULT 'PENDING',

    approved_by BIGINT,
    approved_at TIMESTAMPTZ,

    occurred_at TIMESTAMPTZ NOT NULL,

    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_adjustment_shift
        FOREIGN KEY (shift_id)
        REFERENCES reconciliation.shift (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_adjustment_employee
        FOREIGN KEY (employee_id)
        REFERENCES reconciliation.employee (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_adjustment_approved_by
        FOREIGN KEY (approved_by)
        REFERENCES reconciliation.application_user (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_adjustment_created_by
        FOREIGN KEY (created_by)
        REFERENCES reconciliation.application_user (id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_adjustment_type
        CHECK (
            adjustment_type IN (
                'EXPENSE',
                'CASH_DEPOSIT',
                'FUEL_TESTING',
                'CALIBRATION',
                'FUEL_RETURN',
                'OTHER'
            )
        ),

    CONSTRAINT ck_adjustment_direction
        CHECK (
            direction IN (
                'ADD_TO_ACCOUNTED_AMOUNT',
                'DEDUCT_FROM_ACCOUNTED_AMOUNT'
            )
        ),

    CONSTRAINT ck_adjustment_amount_positive
        CHECK (
            amount > 0
        ),

    CONSTRAINT ck_adjustment_description_not_blank
        CHECK (
            BTRIM(description) <> ''
        ),

    CONSTRAINT ck_adjustment_approval_status
        CHECK (
            approval_status IN (
                'PENDING',
                'APPROVED',
                'REJECTED'
            )
        ),

    CONSTRAINT ck_adjustment_approval
        CHECK (
            approval_status <> 'APPROVED'
            OR (
                approved_by IS NOT NULL
                AND approved_at IS NOT NULL
            )
        )
);


-- ============================================================
-- 7. Indexes
-- ============================================================


-- Fuel Sale
-- ============================================================

CREATE INDEX idx_fuel_sale_shift_employee
    ON reconciliation.fuel_sale (
        shift_id,
        employee_id
    );


CREATE INDEX idx_fuel_sale_shift_fuel_type
    ON reconciliation.fuel_sale (
        shift_id,
        fuel_type_id
    );


CREATE INDEX idx_fuel_sale_nozzle
    ON reconciliation.fuel_sale (
        nozzle_id
    );


CREATE INDEX idx_fuel_sale_shift_nozzle_assignment
    ON reconciliation.fuel_sale (
        shift_nozzle_assignment_id
    );


CREATE INDEX idx_fuel_sale_fuel_price
    ON reconciliation.fuel_sale (
        fuel_price_id
    );


-- Cash Denomination Entry
-- ============================================================

CREATE INDEX idx_cash_denomination_entry_shift_employee
    ON reconciliation.cash_denomination_entry (
        shift_id,
        employee_id
    );


-- Coins Entry
-- ============================================================

CREATE INDEX idx_coins_entry_shift
    ON reconciliation.coins_entry (
        shift_id
    );


CREATE INDEX idx_coins_entry_employee
    ON reconciliation.coins_entry (
        employee_id
    );


-- TID Collection
-- ============================================================

CREATE INDEX idx_tid_collection_shift
    ON reconciliation.tid_collection (
        shift_id
    );


CREATE INDEX idx_tid_collection_employee
    ON reconciliation.tid_collection (
        employee_id
    );


CREATE INDEX idx_tid_collection_terminal
    ON reconciliation.tid_collection (
        terminal_identifier
    );


-- Credit Sale
-- ============================================================

CREATE INDEX idx_credit_sale_shift_employee
    ON reconciliation.credit_sale (
        shift_id,
        employee_id
    );


CREATE INDEX idx_credit_sale_settlement_status
    ON reconciliation.credit_sale (
        settlement_status
    );


-- Adjustment
-- ============================================================

CREATE INDEX idx_adjustment_shift_employee
    ON reconciliation.adjustment (
        shift_id,
        employee_id
    );


CREATE INDEX idx_adjustment_approval_status
    ON reconciliation.adjustment (
        approval_status
    );