-- ============================================================
-- Fuel Station Shift Reconciliation System
-- Database Migration V9
--
-- Purpose:
--   1. Introduce configurable organization-level adjustment types.
--   2. Refactor adjustment transactions to use adjustment_type.
--   3. Create shift-level reconciliation.
--   4. Create employee-level reconciliation.
--   5. Preserve reconciliation submission/resubmission history.
--   6. Preserve Level-1 and Level-2 approval decision history.
--
-- Reconciliation formulas:
--
--   Total Notes Amount =
--       SUM(cash_denomination_entry.calculated_amount)
--
--   Cash Total =
--       Total Notes Amount + Coins Total
--
--   Accounted Amount =
--       Cash Total
--       + TID Device Total
--       + Credit Sale Total
--       + Additive Adjustment Total
--       - Deductive Adjustment Total
--
--   Difference Amount =
--       Accounted Amount - Expected Sales Amount
--
--   Reconciliation Status:
--
--       ABS(Difference Amount) <= Allowed Tolerance
--           => MATCHED
--
--       Difference Amount < -Allowed Tolerance
--           => SHORTAGE
--
--       Difference Amount > Allowed Tolerance
--           => EXCESS
--
-- Previous reconciliation versions, submissions and approval
-- decisions shall remain historically traceable.
-- ============================================================


-- ============================================================
-- 1. Adjustment Type
--
-- Organization-level configurable adjustment master.
--
-- Example:
--
--   EXPENSE
--       direction = DEDUCT_FROM_ACCOUNTED_AMOUNT
--
--   FUEL_RETURN
--       direction = ADD_TO_ACCOUNTED_AMOUNT
--
-- Employees select an adjustment type.
-- They do NOT select the accounting direction.
-- ============================================================

CREATE TABLE reconciliation.adjustment_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id BIGINT NOT NULL,

    adjustment_type_code VARCHAR(50) NOT NULL,
    adjustment_type_name VARCHAR(150) NOT NULL,

    direction VARCHAR(40) NOT NULL,

    requires_approval BOOLEAN NOT NULL DEFAULT TRUE,

    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ,
    updated_by BIGINT,

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_adjustment_type_organization
        FOREIGN KEY (organization_id)
        REFERENCES reconciliation.organization (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_adjustment_type_organization_code
        UNIQUE (
            organization_id,
            adjustment_type_code
        ),

    CONSTRAINT ck_adjustment_type_code_not_blank
        CHECK (
            BTRIM(adjustment_type_code) <> ''
        ),

    CONSTRAINT ck_adjustment_type_name_not_blank
        CHECK (
            BTRIM(adjustment_type_name) <> ''
        ),

    CONSTRAINT ck_adjustment_type_direction
        CHECK (
            direction IN (
                'ADD_TO_ACCOUNTED_AMOUNT',
                'DEDUCT_FROM_ACCOUNTED_AMOUNT'
            )
        )
);


-- ============================================================
-- 2. Refactor Adjustment
--
-- V8 stored adjustment_type and direction directly as
-- hard-coded text values.
--
-- V9 replaces those fields with:
--
--   adjustment_type_id
--
-- and transaction snapshots:
--
--   adjustment_type_code_snapshot
--   adjustment_type_name_snapshot
--   direction_snapshot
--
-- The snapshots ensure that later changes to master
-- configuration cannot alter historical reconciliation.
--
-- The adjustment table is empty when this migration is first
-- introduced, therefore no legacy row conversion is required.
-- ============================================================

ALTER TABLE reconciliation.adjustment
    DROP CONSTRAINT ck_adjustment_type;

ALTER TABLE reconciliation.adjustment
    DROP CONSTRAINT ck_adjustment_direction;


ALTER TABLE reconciliation.adjustment
    ADD COLUMN adjustment_type_id BIGINT;

ALTER TABLE reconciliation.adjustment
    ADD COLUMN adjustment_type_code_snapshot VARCHAR(50);

ALTER TABLE reconciliation.adjustment
    ADD COLUMN adjustment_type_name_snapshot VARCHAR(150);

ALTER TABLE reconciliation.adjustment
    ADD COLUMN direction_snapshot VARCHAR(40);


ALTER TABLE reconciliation.adjustment
    DROP COLUMN adjustment_type;

ALTER TABLE reconciliation.adjustment
    DROP COLUMN direction;


ALTER TABLE reconciliation.adjustment
    ALTER COLUMN adjustment_type_id SET NOT NULL;

ALTER TABLE reconciliation.adjustment
    ALTER COLUMN adjustment_type_code_snapshot SET NOT NULL;

ALTER TABLE reconciliation.adjustment
    ALTER COLUMN adjustment_type_name_snapshot SET NOT NULL;

ALTER TABLE reconciliation.adjustment
    ALTER COLUMN direction_snapshot SET NOT NULL;


ALTER TABLE reconciliation.adjustment
    ADD CONSTRAINT fk_adjustment_adjustment_type
        FOREIGN KEY (adjustment_type_id)
        REFERENCES reconciliation.adjustment_type (id)
        ON DELETE RESTRICT;


ALTER TABLE reconciliation.adjustment
    ADD CONSTRAINT ck_adjustment_type_code_snapshot_not_blank
        CHECK (
            BTRIM(adjustment_type_code_snapshot) <> ''
        );

ALTER TABLE reconciliation.adjustment
    ADD CONSTRAINT ck_adjustment_type_name_snapshot_not_blank
        CHECK (
            BTRIM(adjustment_type_name_snapshot) <> ''
        );

ALTER TABLE reconciliation.adjustment
    ADD CONSTRAINT ck_adjustment_direction_snapshot
        CHECK (
            direction_snapshot IN (
                'ADD_TO_ACCOUNTED_AMOUNT',
                'DEDUCT_FROM_ACCOUNTED_AMOUNT'
            )
        );


-- ============================================================
-- 3. Reconciliation
--
-- Stores one version of the complete shift reconciliation.
--
-- Recalculation creates a new calculation_version rather than
-- silently overwriting the previous result.
--
-- Financial result and approval workflow are deliberately
-- separate:
--
-- reconciliation_status:
--     MATCHED / SHORTAGE / EXCESS
--
-- approval_workflow_status:
--     DRAFT
--     PENDING_LEVEL_1_REVIEW
--     RETURNED_TO_EMPLOYEE
--     RESUBMITTED
--     LEVEL_1_APPROVED
--     LEVEL_1_APPROVED_WITH_REMARKS
--     PENDING_LEVEL_2_APPROVAL
--     APPROVED
-- ============================================================

CREATE TABLE reconciliation.reconciliation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    shift_id BIGINT NOT NULL,

    calculation_version INTEGER NOT NULL,

    expected_sales_amount NUMERIC(19, 2) NOT NULL,

    total_notes_amount NUMERIC(19, 2) NOT NULL,
    coins_total NUMERIC(19, 2) NOT NULL,
    cash_total NUMERIC(19, 2) NOT NULL,

    tid_total NUMERIC(19, 2) NOT NULL,
    credit_total NUMERIC(19, 2) NOT NULL,

    additive_adjustment_total NUMERIC(19, 2) NOT NULL,
    deductive_adjustment_total NUMERIC(19, 2) NOT NULL,

    accounted_amount NUMERIC(19, 2) NOT NULL,
    difference_amount NUMERIC(19, 2) NOT NULL,

    allowed_tolerance NUMERIC(19, 2) NOT NULL,

    reconciliation_status VARCHAR(40) NOT NULL,

    approval_workflow_status VARCHAR(50) NOT NULL
        DEFAULT 'DRAFT',

    level_1_reviewer_id BIGINT,
    level_2_approver_id BIGINT,

    calculated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    calculated_by BIGINT NOT NULL,

    calculation_reason VARCHAR(1000),

    final_approved_by BIGINT,
    final_approved_at TIMESTAMPTZ,

    remarks VARCHAR(1000),

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_reconciliation_shift
        FOREIGN KEY (shift_id)
        REFERENCES reconciliation.shift (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_reconciliation_calculated_by
        FOREIGN KEY (calculated_by)
        REFERENCES reconciliation.application_user (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_reconciliation_level_1_reviewer
        FOREIGN KEY (level_1_reviewer_id)
        REFERENCES reconciliation.application_user (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_reconciliation_level_2_approver
        FOREIGN KEY (level_2_approver_id)
        REFERENCES reconciliation.application_user (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_reconciliation_final_approved_by
        FOREIGN KEY (final_approved_by)
        REFERENCES reconciliation.application_user (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_reconciliation_shift_version
        UNIQUE (
            shift_id,
            calculation_version
        ),

    CONSTRAINT ck_reconciliation_calculation_version
        CHECK (
            calculation_version > 0
        ),

    CONSTRAINT ck_reconciliation_expected_sales
        CHECK (
            expected_sales_amount >= 0
        ),

    CONSTRAINT ck_reconciliation_total_notes
        CHECK (
            total_notes_amount >= 0
        ),

    CONSTRAINT ck_reconciliation_coins
        CHECK (
            coins_total >= 0
        ),

    CONSTRAINT ck_reconciliation_cash
        CHECK (
            cash_total >= 0
        ),

    CONSTRAINT ck_reconciliation_tid
        CHECK (
            tid_total >= 0
        ),

    CONSTRAINT ck_reconciliation_credit
        CHECK (
            credit_total >= 0
        ),

    CONSTRAINT ck_reconciliation_additive_adjustment
        CHECK (
            additive_adjustment_total >= 0
        ),

    CONSTRAINT ck_reconciliation_deductive_adjustment
        CHECK (
            deductive_adjustment_total >= 0
        ),

    CONSTRAINT ck_reconciliation_tolerance
        CHECK (
            allowed_tolerance >= 0
        ),

    CONSTRAINT ck_reconciliation_cash_formula
        CHECK (
            cash_total =
                total_notes_amount + coins_total
        ),

    CONSTRAINT ck_reconciliation_accounted_formula
        CHECK (
            accounted_amount =
                  cash_total
                + tid_total
                + credit_total
                + additive_adjustment_total
                - deductive_adjustment_total
        ),

    CONSTRAINT ck_reconciliation_difference_formula
        CHECK (
            difference_amount =
                accounted_amount - expected_sales_amount
        ),

    CONSTRAINT ck_reconciliation_status
        CHECK (
            reconciliation_status IN (
                'MATCHED',
                'SHORTAGE',
                'EXCESS'
            )
        ),

    CONSTRAINT ck_reconciliation_status_matches_difference
        CHECK (
            (
                reconciliation_status = 'MATCHED'
                AND ABS(difference_amount) <= allowed_tolerance
            )
            OR
            (
                reconciliation_status = 'SHORTAGE'
                AND difference_amount < -allowed_tolerance
            )
            OR
            (
                reconciliation_status = 'EXCESS'
                AND difference_amount > allowed_tolerance
            )
        ),

    CONSTRAINT ck_reconciliation_workflow_status
        CHECK (
            approval_workflow_status IN (
                'DRAFT',
                'PENDING_LEVEL_1_REVIEW',
                'RETURNED_TO_EMPLOYEE',
                'RESUBMITTED',
                'LEVEL_1_APPROVED',
                'LEVEL_1_APPROVED_WITH_REMARKS',
                'PENDING_LEVEL_2_APPROVAL',
                'APPROVED'
            )
        ),

    CONSTRAINT ck_reconciliation_final_approval
        CHECK (
            (
                approval_workflow_status <> 'APPROVED'
                AND final_approved_by IS NULL
                AND final_approved_at IS NULL
            )
            OR
            (
                approval_workflow_status = 'APPROVED'
                AND final_approved_by IS NOT NULL
                AND final_approved_at IS NOT NULL
            )
        )
);


-- ============================================================
-- 4. Employee Reconciliation
--
-- Stores one employee's contribution to one shift-level
-- reconciliation version.
--
-- shift_employee_id explicitly ties the financial result to the
-- employee's actual shift participation.
-- ============================================================

CREATE TABLE reconciliation.employee_reconciliation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    reconciliation_id BIGINT NOT NULL,

    shift_employee_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,

    expected_sales_amount NUMERIC(19, 2) NOT NULL,

    total_notes_amount NUMERIC(19, 2) NOT NULL,
    coins_total NUMERIC(19, 2) NOT NULL,
    cash_total NUMERIC(19, 2) NOT NULL,

    tid_total NUMERIC(19, 2) NOT NULL,
    credit_total NUMERIC(19, 2) NOT NULL,

    additive_adjustment_total NUMERIC(19, 2) NOT NULL,
    deductive_adjustment_total NUMERIC(19, 2) NOT NULL,

    accounted_amount NUMERIC(19, 2) NOT NULL,
    difference_amount NUMERIC(19, 2) NOT NULL,

    allowed_tolerance NUMERIC(19, 2) NOT NULL,

    reconciliation_status VARCHAR(40) NOT NULL,

    CONSTRAINT fk_employee_reconciliation_reconciliation
        FOREIGN KEY (reconciliation_id)
        REFERENCES reconciliation.reconciliation (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_employee_reconciliation_shift_employee
        FOREIGN KEY (shift_employee_id)
        REFERENCES reconciliation.shift_employee (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_employee_reconciliation_employee
        FOREIGN KEY (employee_id)
        REFERENCES reconciliation.employee (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_employee_reconciliation
        UNIQUE (
            reconciliation_id,
            shift_employee_id
        ),

    CONSTRAINT ck_employee_reconciliation_expected_sales
        CHECK (
            expected_sales_amount >= 0
        ),

    CONSTRAINT ck_employee_reconciliation_total_notes
        CHECK (
            total_notes_amount >= 0
        ),

    CONSTRAINT ck_employee_reconciliation_coins
        CHECK (
            coins_total >= 0
        ),

    CONSTRAINT ck_employee_reconciliation_cash
        CHECK (
            cash_total >= 0
        ),

    CONSTRAINT ck_employee_reconciliation_tid
        CHECK (
            tid_total >= 0
        ),

    CONSTRAINT ck_employee_reconciliation_credit
        CHECK (
            credit_total >= 0
        ),

    CONSTRAINT ck_employee_reconciliation_additive_adjustment
        CHECK (
            additive_adjustment_total >= 0
        ),

    CONSTRAINT ck_employee_reconciliation_deductive_adjustment
        CHECK (
            deductive_adjustment_total >= 0
        ),

    CONSTRAINT ck_employee_reconciliation_tolerance
        CHECK (
            allowed_tolerance >= 0
        ),

    CONSTRAINT ck_employee_reconciliation_cash_formula
        CHECK (
            cash_total =
                total_notes_amount + coins_total
        ),

    CONSTRAINT ck_employee_reconciliation_accounted_formula
        CHECK (
            accounted_amount =
                  cash_total
                + tid_total
                + credit_total
                + additive_adjustment_total
                - deductive_adjustment_total
        ),

    CONSTRAINT ck_employee_reconciliation_difference_formula
        CHECK (
            difference_amount =
                accounted_amount - expected_sales_amount
        ),

    CONSTRAINT ck_employee_reconciliation_status
        CHECK (
            reconciliation_status IN (
                'MATCHED',
                'SHORTAGE',
                'EXCESS'
            )
        ),

    CONSTRAINT ck_employee_reconciliation_status_difference
        CHECK (
            (
                reconciliation_status = 'MATCHED'
                AND ABS(difference_amount) <= allowed_tolerance
            )
            OR
            (
                reconciliation_status = 'SHORTAGE'
                AND difference_amount < -allowed_tolerance
            )
            OR
            (
                reconciliation_status = 'EXCESS'
                AND difference_amount > allowed_tolerance
            )
        )
);


-- ============================================================
-- 5. Reconciliation Submission
--
-- Append-only history of initial submission and every
-- resubmission.
--
-- Submission Number:
--
--     1 = INITIAL
--     2+ = RESUBMISSION
--
-- Application validation shall enforce the sequence.
-- ============================================================

CREATE TABLE reconciliation.reconciliation_submission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    reconciliation_id BIGINT NOT NULL,

    submission_number INTEGER NOT NULL,

    submission_type VARCHAR(20) NOT NULL,

    submitted_by BIGINT NOT NULL,
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    remarks VARCHAR(1000),

    CONSTRAINT fk_reconciliation_submission_reconciliation
        FOREIGN KEY (reconciliation_id)
        REFERENCES reconciliation.reconciliation (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_reconciliation_submission_submitted_by
        FOREIGN KEY (submitted_by)
        REFERENCES reconciliation.application_user (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_reconciliation_submission_number
        UNIQUE (
            reconciliation_id,
            submission_number
        ),

    CONSTRAINT ck_reconciliation_submission_number
        CHECK (
            submission_number > 0
        ),

    CONSTRAINT ck_reconciliation_submission_type
        CHECK (
            submission_type IN (
                'INITIAL',
                'RESUBMISSION'
            )
        ),

    CONSTRAINT ck_reconciliation_initial_submission
        CHECK (
            (
                submission_number = 1
                AND submission_type = 'INITIAL'
            )
            OR
            (
                submission_number > 1
                AND submission_type = 'RESUBMISSION'
            )
        )
);


-- ============================================================
-- 6. Approval Decision
--
-- Append-only Level-1 and Level-2 approval history.
--
-- Level-1:
--
--   MATCHED
--       APPROVED
--
--   SHORTAGE / EXCESS
--       RETURNED_TO_EMPLOYEE
--
--   Persistent shortage/excess after resubmission
--       APPROVED_WITH_REMARKS
--
-- Level-2:
--
--       APPROVED
--       APPROVED_WITH_REMARKS
--       REJECTED
--
-- A Level-2 REJECTED decision transitions the workflow back to
-- RETURNED_TO_EMPLOYEE so corrections and resubmission can occur.
-- ============================================================

CREATE TABLE reconciliation.approval_decision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    reconciliation_id BIGINT NOT NULL,

    reconciliation_submission_id BIGINT NOT NULL,

    submission_number INTEGER NOT NULL,

    approval_level VARCHAR(20) NOT NULL,

    action VARCHAR(40) NOT NULL,

    acted_by BIGINT NOT NULL,
    acted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    remarks VARCHAR(1000),
    reason VARCHAR(1000),

    previous_workflow_status VARCHAR(50) NOT NULL,
    new_workflow_status VARCHAR(50) NOT NULL,

    CONSTRAINT fk_approval_decision_reconciliation
        FOREIGN KEY (reconciliation_id)
        REFERENCES reconciliation.reconciliation (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_approval_decision_submission
        FOREIGN KEY (reconciliation_submission_id)
        REFERENCES reconciliation.reconciliation_submission (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_approval_decision_acted_by
        FOREIGN KEY (acted_by)
        REFERENCES reconciliation.application_user (id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_approval_decision_submission_number
        CHECK (
            submission_number > 0
        ),

    CONSTRAINT ck_approval_decision_level
        CHECK (
            approval_level IN (
                'LEVEL_1',
                'LEVEL_2'
            )
        ),

    CONSTRAINT ck_approval_decision_action
        CHECK (
            action IN (
                'SUBMITTED',
                'RETURNED_TO_EMPLOYEE',
                'RESUBMITTED',
                'APPROVED',
                'APPROVED_WITH_REMARKS',
                'REJECTED'
            )
        ),

    CONSTRAINT ck_approval_decision_return_reason
        CHECK (
            action NOT IN (
                'RETURNED_TO_EMPLOYEE',
                'REJECTED'
            )
            OR (
                reason IS NOT NULL
                AND BTRIM(reason) <> ''
            )
        ),

    CONSTRAINT ck_approval_decision_remarks
        CHECK (
            action <> 'APPROVED_WITH_REMARKS'
            OR (
                remarks IS NOT NULL
                AND BTRIM(remarks) <> ''
            )
        ),

    CONSTRAINT ck_approval_decision_previous_status_not_blank
        CHECK (
            BTRIM(previous_workflow_status) <> ''
        ),

    CONSTRAINT ck_approval_decision_new_status_not_blank
        CHECK (
            BTRIM(new_workflow_status) <> ''
        )
);


-- ============================================================
-- 7. Indexes
-- ============================================================


-- Adjustment Type
-- ============================================================

CREATE INDEX idx_adjustment_type_organization_active
    ON reconciliation.adjustment_type (
        organization_id,
        active
    );


-- Adjustment
-- ============================================================

CREATE INDEX idx_adjustment_adjustment_type
    ON reconciliation.adjustment (
        adjustment_type_id
    );


-- Reconciliation
-- ============================================================

CREATE INDEX idx_reconciliation_shift
    ON reconciliation.reconciliation (
        shift_id
    );


CREATE INDEX idx_reconciliation_status
    ON reconciliation.reconciliation (
        reconciliation_status
    );


CREATE INDEX idx_reconciliation_workflow_status
    ON reconciliation.reconciliation (
        approval_workflow_status
    );


CREATE INDEX idx_reconciliation_calculated_at
    ON reconciliation.reconciliation (
        calculated_at
    );


CREATE INDEX idx_reconciliation_level_1_reviewer
    ON reconciliation.reconciliation (
        level_1_reviewer_id
    );


CREATE INDEX idx_reconciliation_level_2_approver
    ON reconciliation.reconciliation (
        level_2_approver_id
    );


-- Employee Reconciliation
-- ============================================================

CREATE INDEX idx_employee_reconciliation_reconciliation
    ON reconciliation.employee_reconciliation (
        reconciliation_id
    );


CREATE INDEX idx_employee_reconciliation_employee
    ON reconciliation.employee_reconciliation (
        employee_id
    );


CREATE INDEX idx_employee_reconciliation_shift_employee
    ON reconciliation.employee_reconciliation (
        shift_employee_id
    );


CREATE INDEX idx_employee_reconciliation_status
    ON reconciliation.employee_reconciliation (
        reconciliation_status
    );


-- Reconciliation Submission
-- ============================================================

CREATE INDEX idx_reconciliation_submission_reconciliation
    ON reconciliation.reconciliation_submission (
        reconciliation_id
    );


CREATE INDEX idx_reconciliation_submission_submitted_at
    ON reconciliation.reconciliation_submission (
        submitted_at
    );


-- Approval Decision
-- ============================================================

CREATE INDEX idx_approval_decision_reconciliation
    ON reconciliation.approval_decision (
        reconciliation_id
    );


CREATE INDEX idx_approval_decision_submission
    ON reconciliation.approval_decision (
        reconciliation_submission_id
    );


CREATE INDEX idx_approval_decision_level
    ON reconciliation.approval_decision (
        approval_level
    );


CREATE INDEX idx_approval_decision_acted_at
    ON reconciliation.approval_decision (
        acted_at
    );


CREATE INDEX idx_approval_decision_acted_by
    ON reconciliation.approval_decision (
        acted_by
    );